# Generated by Django 5.0 on 2024-01-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('Archivo', 'Archivo'), ('Widgets', 'Widgets'), ('Lista Inteligente', 'Lista Inteligente')], max_length=17)),
                ('file', models.CharField(max_length=100)),
                ('audio_en_video', models.BooleanField()),
                ('listo', models.BooleanField()),
                ('alta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pantalla',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='ruta_de_guardado/')),
                ('nombre', models.CharField(max_length=200)),
                ('estado', models.BooleanField()),
                ('ancho_en_pixeles', models.IntegerField()),
                ('alto_en_pixeles', models.IntegerField()),
                ('tiempo_cada_espacio_seg', models.IntegerField()),
                ('nro_espacios_publicitarios', models.IntegerField()),
                ('salidas_minimas_por_hora', models.IntegerField()),
                ('carpeta', models.CharField(max_length=45)),
                ('lunes', models.BooleanField()),
                ('martes', models.BooleanField()),
                ('miercoles', models.BooleanField()),
                ('jueves', models.BooleanField()),
                ('viernes', models.BooleanField()),
                ('sabado', models.BooleanField()),
                ('domingo', models.BooleanField()),
            ],
        ),
    ]
