# Generated by Django 5.0 on 2024-01-16 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pantalla',
            name='carpeta',
        ),
    ]
