# Generated by Django 5.0 on 2024-01-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0002_remove_pantalla_carpeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='file',
            field=models.FileField(null=True, upload_to='videos_imagenes'),
        ),
    ]
