# Generated by Django 5.0 on 2024-01-17 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0003_alter_anuncio_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmsAnuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='anuncios/')),
                ('multiplicador', models.IntegerField()),
                ('autoeliminacion', models.BooleanField()),
                ('play_exclusivo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=10)),
                ('fecha_inicial', models.DateField()),
                ('fecha_final', models.DateField()),
                ('hora_inicial', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuncios.cmsanuncio')),
            ],
        ),
    ]
