# Generated by Django 5.0 on 2024-01-17 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0004_cmsanuncio_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='anuncio',
        ),
        migrations.DeleteModel(
            name='CmsAnuncio',
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
    ]
