# Generated by Django 5.0 on 2024-01-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0005_remove_horario_anuncio_delete_cmsanuncio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/')),
                ('fecha_inicial', models.DateField()),
                ('fecha_final', models.DateField()),
                ('dias_activos', models.CharField(max_length=7)),
                ('hora_inicial', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('tiempo_video', models.CharField(blank=True, max_length=10, null=True)),
                ('multiplicador', models.IntegerField(blank=True, null=True)),
                ('autoeliminacion', models.BooleanField()),
                ('play_exclusivo', models.BooleanField()),
            ],
        ),
    ]
