# Generated by Django 5.0 on 2024-01-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0007_alter_cmsevent_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.TimeField()),
                ('fin', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cmsevent',
            name='fecha_final',
        ),
        migrations.RemoveField(
            model_name='cmsevent',
            name='fecha_inicial',
        ),
        migrations.RemoveField(
            model_name='cmsevent',
            name='hora_final',
        ),
        migrations.RemoveField(
            model_name='cmsevent',
            name='hora_inicial',
        ),
        migrations.AlterField(
            model_name='cmsevent',
            name='autoeliminacion',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='cmsevent',
            name='dias_activos',
        ),
        migrations.AlterField(
            model_name='cmsevent',
            name='file',
            field=models.FileField(null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='cmsevent',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cmsevent',
            name='play_exclusivo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cmsevent',
            name='tiempo_video',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cmsevent',
            name='fechas',
            field=models.ManyToManyField(to='anuncios.fecha'),
        ),
        migrations.AddField(
            model_name='cmsevent',
            name='horarios',
            field=models.ManyToManyField(to='anuncios.horario'),
        ),
        migrations.AddField(
            model_name='cmsevent',
            name='dias_activos',
            field=models.ManyToManyField(to='anuncios.dia'),
        ),
    ]
