# Generated by Django 5.0 on 2024-01-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0009_remove_cmsevent_dias_activos_remove_cmsevent_fechas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmsevent',
            name='fechas',
        ),
        migrations.RemoveField(
            model_name='cmsevent',
            name='horarios',
        ),
        migrations.AddField(
            model_name='cmsevent',
            name='fecha_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cmsevent',
            name='fecha_inicial',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cmsevent',
            name='hora_final',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cmsevent',
            name='hora_inicial',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
