# Generated by Django 5.0 on 2024-01-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0010_remove_cmsevent_fechas_remove_cmsevent_horarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsevent',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
