# Generated by Django 5.0 on 2024-01-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0011_alter_cmsevent_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='cmsevent',
            name='dias_activos',
        ),
        migrations.AddField(
            model_name='cmsevent',
            name='dias_activos',
            field=models.ManyToManyField(blank=True, to='anuncios.day'),
        ),
    ]
