# Generated by Django 5.0 on 2024-01-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0012_day_remove_cmsevent_dias_activos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmsevent',
            name='dias_activos',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.AddField(
            model_name='cmsevent',
            name='dias_activos',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
