# Generated by Django 5.0 on 2024-01-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0013_remove_cmsevent_dias_activos_delete_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cmsevent',
            name='dias_activos',
        ),
        migrations.AddField(
            model_name='cmsevent',
            name='dias_activos',
            field=models.ManyToManyField(blank=True, to='anuncios.diaactivo'),
        ),
    ]
