# Generated by Django 5.0 on 2024-01-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0014_diaactivo_remove_cmsevent_dias_activos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmsevent',
            name='dias_activos',
        ),
        migrations.AddField(
            model_name='cmsevent',
            name='domingo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cmsevent',
            name='jueves',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cmsevent',
            name='lunes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cmsevent',
            name='martes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cmsevent',
            name='miercoles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cmsevent',
            name='sabado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cmsevent',
            name='viernes',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='DiaActivo',
        ),
    ]
