# Generated by Django 5.0 on 2024-01-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0015_remove_cmsevent_dias_activos_cmsevent_domingo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsevent',
            name='domingo',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='cmsevent',
            name='jueves',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='cmsevent',
            name='lunes',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='cmsevent',
            name='martes',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='cmsevent',
            name='miercoles',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='cmsevent',
            name='sabado',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='cmsevent',
            name='viernes',
            field=models.BooleanField(),
        ),
    ]
