# Generated by Django 5.0 on 2024-01-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0016_alter_cmsevent_domingo_alter_cmsevent_jueves_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsevent',
            name='fecha_final1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cmsevent',
            name='fecha_final2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cmsevent',
            name='fecha_inicial1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cmsevent',
            name='fecha_inicial2',
            field=models.DateField(blank=True, null=True),
        ),
    ]
