# Generated by Django 5.0 on 2024-01-18 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0017_cmsevent_fecha_final1_cmsevent_fecha_final2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmsevent',
            name='fecha_final1',
        ),
        migrations.RemoveField(
            model_name='cmsevent',
            name='fecha_final2',
        ),
        migrations.RemoveField(
            model_name='cmsevent',
            name='fecha_inicial1',
        ),
        migrations.RemoveField(
            model_name='cmsevent',
            name='fecha_inicial2',
        ),
    ]
